// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSG66rum-sYcMkZyjbL_hIPbSmxgrGCg',
    appId: '1:404124165390:android:2b5128dc68d6386d61235f',
    messagingSenderId: '404124165390',
    projectId: 'ticktick-f0d6e',
    storageBucket: 'ticktick-f0d6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_KfQUWz-jVNlT9w3r8GdQEtVYozGL-pY',
    appId: '1:404124165390:ios:b5737c12975159a261235f',
    messagingSenderId: '404124165390',
    projectId: 'ticktick-f0d6e',
    storageBucket: 'ticktick-f0d6e.firebasestorage.app',
    iosBundleId: 'com.ticktick.example.ticktick',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_KfQUWz-jVNlT9w3r8GdQEtVYozGL-pY',
    appId: '1:404124165390:ios:83535fd66ce715d761235f',
    messagingSenderId: '404124165390',
    projectId: 'ticktick-f0d6e',
    storageBucket: 'ticktick-f0d6e.firebasestorage.app',
    iosBundleId: 'com.ticktick.app',
  );
}
